/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EmailStatus = IDL.Variant({
  'failed' : IDL.Text,
  'sentSuccessfully' : IDL.Null,
});
export const Time = IDL.Int;
export const EmailRecord = IDL.Record({
  'cc' : IDL.Vec(IDL.Text),
  'id' : IDL.Nat,
  'to' : IDL.Vec(IDL.Text),
  'bcc' : IDL.Vec(IDL.Text),
  'status' : EmailStatus,
  'subject' : IDL.Text,
  'body' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'getEmail' : IDL.Func([IDL.Nat], [EmailRecord], ['query']),
  'getEmailHistory' : IDL.Func([], [IDL.Vec(EmailRecord)], ['query']),
  'sendAndRecordEmail' : IDL.Func(
      [
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EmailStatus = IDL.Variant({
    'failed' : IDL.Text,
    'sentSuccessfully' : IDL.Null,
  });
  const Time = IDL.Int;
  const EmailRecord = IDL.Record({
    'cc' : IDL.Vec(IDL.Text),
    'id' : IDL.Nat,
    'to' : IDL.Vec(IDL.Text),
    'bcc' : IDL.Vec(IDL.Text),
    'status' : EmailStatus,
    'subject' : IDL.Text,
    'body' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'getEmail' : IDL.Func([IDL.Nat], [EmailRecord], ['query']),
    'getEmailHistory' : IDL.Func([], [IDL.Vec(EmailRecord)], ['query']),
    'sendAndRecordEmail' : IDL.Func(
        [
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };