/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface EmailRecord {
  'cc' : Array<string>,
  'id' : bigint,
  'to' : Array<string>,
  'bcc' : Array<string>,
  'status' : EmailStatus,
  'subject' : string,
  'body' : string,
  'timestamp' : Time,
}
export type EmailStatus = { 'failed' : string } |
  { 'sentSuccessfully' : null };
export type Time = bigint;
export interface _SERVICE {
  'getEmail' : ActorMethod<[bigint], EmailRecord>,
  'getEmailHistory' : ActorMethod<[], Array<EmailRecord>>,
  'sendAndRecordEmail' : ActorMethod<
    [Array<string>, Array<string>, Array<string>, string, string],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];