/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type EmailStatus = {
    __kind__: "failed";
    failed: string;
} | {
    __kind__: "sentSuccessfully";
    sentSuccessfully: null;
};
export type Time = bigint;
export interface EmailRecord {
    cc: Array<string>;
    id: bigint;
    to: Array<string>;
    bcc: Array<string>;
    status: EmailStatus;
    subject: string;
    body: string;
    timestamp: Time;
}
export interface backendInterface {
    getEmail(id: bigint): Promise<EmailRecord>;
    getEmailHistory(): Promise<Array<EmailRecord>>;
    sendAndRecordEmail(to: Array<string>, cc: Array<string>, bcc: Array<string>, subject: string, body: string): Promise<bigint>;
}
import type { EmailRecord as _EmailRecord, EmailStatus as _EmailStatus, Time as _Time } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getEmail(arg0: bigint): Promise<EmailRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmail(arg0);
                return from_candid_EmailRecord_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmail(arg0);
            return from_candid_EmailRecord_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmailHistory(): Promise<Array<EmailRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmailHistory();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmailHistory();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendAndRecordEmail(arg0: Array<string>, arg1: Array<string>, arg2: Array<string>, arg3: string, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.sendAndRecordEmail(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendAndRecordEmail(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
}
function from_candid_EmailRecord_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmailRecord): EmailRecord {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_EmailStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmailStatus): EmailStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cc: Array<string>;
    id: bigint;
    to: Array<string>;
    bcc: Array<string>;
    status: _EmailStatus;
    subject: string;
    body: string;
    timestamp: _Time;
}): {
    cc: Array<string>;
    id: bigint;
    to: Array<string>;
    bcc: Array<string>;
    status: EmailStatus;
    subject: string;
    body: string;
    timestamp: Time;
} {
    return {
        cc: value.cc,
        id: value.id,
        to: value.to,
        bcc: value.bcc,
        status: from_candid_EmailStatus_n3(_uploadFile, _downloadFile, value.status),
        subject: value.subject,
        body: value.body,
        timestamp: value.timestamp
    };
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    failed: string;
} | {
    sentSuccessfully: null;
}): {
    __kind__: "failed";
    failed: string;
} | {
    __kind__: "sentSuccessfully";
    sentSuccessfully: null;
} {
    return "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : "sentSuccessfully" in value ? {
        __kind__: "sentSuccessfully",
        sentSuccessfully: value.sentSuccessfully
    } : value;
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmailRecord>): Array<EmailRecord> {
    return value.map((x)=>from_candid_EmailRecord_n1(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
